services:

  # Node.js Frontend Service
  - type: web
    name: object-detection-frontend
    runtime: node
    buildCommand: "npm install"
    startCommand: "node server.cjs" 
    envVars:
      - key: ML_SERVICE_URL
        fromService:
          type: web
          name: object-detection-ml
          property: host
    plan: free
    